export const post_content: string;
export const post_content_inside: string;
export const title: string;
export const content: string;
export const vote_select: string;
export const submit_button: string;
export const date_button: string;
export const mini_header: string;
export const mini_header_inside: string;
export const search_bar: string;
export const header_box: string;
export const header_inner:string;
export const mini_header_item:string;