export const header: string;
export const li: string;
export const title: string;
export const content: string;
export const menu: string;
export const menulist: string;
export const created_at: string;
export const vote_section: string;
export const each_post: string;
export const feed: string;
export const ul: string;
export const footer: string;
export const plotly: string;
// export const vote_ul: string;
export const vote_ul: string;
export const each_post_link: string;
